// <auto-generated />
using System;
using Gateway.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gateway.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    partial class GatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gateway.Domain.Entities.ProxyRequestEvent", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("ClientIp").HasMaxLength(45).HasColumnType("character varying(45)");
                    b.Property<DateTime>("CompletedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("ConfiguredDestination").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)");
                    b.Property<double?>("DurationMs").HasColumnType("double precision");
                    b.Property<Guid>("EndpointId").HasColumnType("uuid");
                    b.Property<string>("EndpointName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<Guid>("GroupId").HasColumnType("uuid");
                    b.Property<string>("GroupName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Method").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
                    b.Property<DateTime>("OccurredAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Outcome").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<string>("RequestPath").IsRequired().HasMaxLength(2048).HasColumnType("character varying(2048)");
                    b.Property<int?>("ResponseStatus").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("EndpointId", "OccurredAt", "Id");
                    b.HasIndex("GroupId", "OccurredAt", "Id");
                    b.HasIndex("OccurredAt", "Id");
                    b.ToTable("ProxyRequestEvents");
                });

            modelBuilder.Entity("Gateway.Domain.Entities.ProxyEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedIpRanges")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("BlockedIpRanges")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RateLimitPerMinute")
                        .HasColumnType("integer");

                    b.Property<string>("RemovePrefix")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresAuth")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("Gateway.Domain.Entities.ProxyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedIpRanges")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("BlockedIpRanges")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Gateway.Domain.Entities.ProxyEndpoint", b =>
                {
                    b.HasOne("Gateway.Domain.Entities.ProxyGroup", "Group")
                        .WithMany("Endpoints")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Gateway.Domain.Entities.ProxyGroup", b =>
                {
                    b.Navigation("Endpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
